services:
  motorbot:
    image: ghcr.io/motorlatitude/motorbot:latest
    restart: unless-stopped
    environment:
      - DATABASE_PATH=${DATABASE_PATH:-/data/}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - RAPID_API_KEY=${RAPID_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - TZ=${TZ:-UTC}
    volumes:
      - data:/data

volumes:
  data:
