use std::fmt::Display;

use serenity::all::{ChannelId, Context, CreateEmbed, CreateMessage};
use tracing::error;

use crate::{
    plugin::MotorbotPlugin,
    storage::{Database, GuildConfigKey, GuildConfigValue},
    Error, Result,
};

/// The context passed to plugins, containing the Serenity context and
/// motorbot specific information such as the list of loaded plugins.
#[derive(Clone)]
pub struct PluginContext<'a> {
    /// The Serenity context, which provides access to Discord API
    pub ctx: Context,
    /// A reference to the list of loaded plugins, allowing plugins to access
    /// information about other plugins if needed.
    pub plugins: &'a Vec<Box<dyn MotorbotPlugin + Send + Sync>>,
}

/// An event generated by a plugin, containing information about the event
/// and its severity level.
pub struct PluginEvent {
    pub level: PluginEventLevel,
    pub name: String,
    pub description: Option<String>,
}

/// The level of a plugin event, indicating its severity or importance.
#[derive(Debug, Default)]
#[allow(unused)]
pub enum PluginEventLevel {
    /// A debug event, used for detailed information that may be useful for
    /// diagnosing issues or understanding the internal workings of the plugin.
    #[default]
    Debug,
    /// An informational event, used for general information about the plugin's
    /// operation or important milestones.
    Info,
    /// A warning event, used for potential issues or situations that may
    /// require attention but are not necessarily errors.
    Warning,
    /// An error event, used for significant issues or errors that may impact the
    /// plugin's functionality or require immediate attention.
    Error,
}

impl PluginEvent {
    pub fn new(level: PluginEventLevel, name: &str) -> Self {
        Self {
            name: name.to_string(),
            description: None,
            level,
        }
    }

    pub fn description(mut self, description: &str) -> Self {
        self.description = Some(description.to_string());
        self
    }
}

impl Display for PluginEventLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Debug => write!(f, "DEBUG"),
            Self::Info => write!(f, "INFO"),
            Self::Warning => write!(f, "WARNING"),
            Self::Error => write!(f, "ERROR"),
        }
    }
}

impl<'a> PluginContext<'a> {
    pub async fn new(
        ctx: Context,
        plugins: &'a Vec<Box<dyn MotorbotPlugin + Send + Sync>>,
    ) -> Self {
        Self { ctx, plugins }
    }

    /// Send a message to the configured bot events channel
    ///
    /// This is a convenience method for plugins to send messages to the bot
    /// events channel without needing to know the channel ID or access the
    /// Serenity context directly.
    ///
    /// Plugins can use this method to log important events or information to
    /// the bot events channel for easier monitoring and debugging.
    pub async fn send_event(&self, event: PluginEvent) -> Result<()> {
        let mut db = Database::open().await?;
        let guilds = self.ctx.cache.guilds();
        let mut event_channel_ids = Vec::new();
        for guild_id in guilds {
            let channel_id: Option<u64> = match db
                .get_guild_config(guild_id.get(), GuildConfigKey::EventsChannel)
                .await
            {
                Ok(Some(config_value)) => match config_value.value {
                    GuildConfigValue::ChannelId(id) => Some(id),
                    _ => None,
                },
                Ok(None) => None,
                Err(why) => {
                    error!(
                        "Error fetching events channel from database: {:?}",
                        why
                    );
                    None
                }
            };
            if let Some(channel_id) = channel_id {
                event_channel_ids.push(channel_id);
            }
        }
        let level_color = match event.level {
            PluginEventLevel::Debug => 0xAAAAAA,
            PluginEventLevel::Info => 0x55B8F9,
            PluginEventLevel::Warning => 0xFAE577,
            PluginEventLevel::Error => 0xFF0000,
        };
        let mut embed_builder = CreateEmbed::default()
            .title(format!("[{}] {}", event.level, event.name))
            .color(level_color);
        if let Some(description) = event.description {
            embed_builder = embed_builder.description(description);
        }
        let builder = CreateMessage::new().embed(embed_builder);
        for channel_id in event_channel_ids {
            ChannelId::new(channel_id)
                .send_message(&self.ctx.http, builder.clone())
                .await
                .map_err(|err| Error::FailedToSendEvent { err })?;
        }
        db.close().await?;
        Ok(())
    }
}
